from datetime import datetime

print("================================")
print("       ATI CRYPTO BOT")
print("================================")
print("MODE: PAPER / TEST")
print("TRADING: DISABLED")
print("TIME:", datetime.now())
print("--------------------------------")
print("SYMBOL: BTCUSDT")
print("TIMEFRAME: 5m")
print("SIGNAL: HOLD")
print("--------------------------------")
print("NO REAL TRADE")
print("================================")
