name: Run ATI Futures Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      TABDIL_API_KEY: ${{ secrets.TABDIL_API_KEY }}
      TABDIL_API_SECRET: ${{ secrets.TABDIL_API_SECRET }}

      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      LIVE_TRADING: ${{ secrets.LIVE_TRADING }}
      ORDER_QTY: ${{ secrets.ORDER_QTY }}
      LEVERAGE: ${{ secrets.LEVERAGE }}

      MAX_NEW_TRADES: ${{ secrets.MAX_NEW_TRADES }}
      SL_PERCENT: ${{ secrets.SL_PERCENT }}
      TP_PERCENT: ${{ secrets.TP_PERCENT }}
      SCAN_LIMIT: ${{ secrets.SCAN_LIMIT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run ATI Futures
        run: |
          python main.py
